### ISSUE TITLE
xml里面设置其他的单位（kgUnitText）

### ISSUE THREAD

**Issue by Ronnys** [totond/BooheeRuler#11]
设置了其他单位之后，单位的textview 就显示未空了。
![image](https://user-images.githubusercontent.com/4937028/32880414-803138e2-cae8-11e7-9e04-adbb2e6e2e1e.png)
initAttrs 方法里面获取到其他单位，会把默认单位置空。init中setText()是null

**Comment by totond** [comment]
不好意思啊，应该是之前手抖了，那个null应该是text，现在最新版本已经改正了。感谢提出的bug啊^_^。
