### ISSUE TITLE
除0

### ISSUE THREAD

**Issue by KingLanding94** [totond/BooheeRuler#12]
//把滑动偏移量scrollX转化为刻度Scale
    private float scrollXtoScale(int scrollX) {
        return ((float) (scrollX - mMinPosition) / mLength) * mMaxLength + mParent.getMinScale();
    }

这个函数会产生 除0 情况。mLength可能为0

**Comment by totond** [comment]
你好，你测试到的这个mLength为0的情况是不是maxScale属性和minScale属性相等，或者scaleInterval属性设置为0的时候呢，因为它初始化的时候的赋值是
```
       mLength = (mParent.getMaxScale() - mParent.getMinScale()) * mParent.getInterval();
```
　　如果不是，能告诉一下当时是怎样的情况吗？例如滑动到某个点，或者Activity有没做出重启操作之类的。

**Comment by KingLanding94** [comment]
不是的。我当时用设定的maxScale是200，minScale是1.但是没有设定currentScale。对于currentScale的设定是在程序里面设定的，当时一直设定不了，然后debug时才发现这个问题。

**Comment by totond** [comment]
Debug的时候是什么时候发现mLength为0呢，因为BooheeRuler的设定一开始mLength就是0的，只有等到InnerRuler初始化才会被赋值。也就是说，执行到什么时候抛出除0异常呢：

```
java.lang.ArithmeticException: divide by zero
```

**Comment by KingLanding94** [comment]
抱歉，刚刚我想到一个问题。我把BooHeeRuler初始化currentScale的那段代码更改了一下。问题应该是出在这里的。抱歉，，

**Comment by KingLanding94** [comment]
函数调用依次是：BooHeeRuler.setCurrentScale() -->InnerRuler.setCurrentScale()-->
HorizontalRuler.goToScale() --> HorizontalRuler.scrollTo() -->HorizontalRuler.scrollXtoScale.在最后这个函数里出现了除0的情况。不过我刚刚想了一下可能因为我在BooHeeRuler更改了mCurrentScale的初始化。所以才导致了除0的情况。如果这样的话，真的很抱歉。。

**Comment by totond** [comment]
没关系，你会不会是把mCurrentScale的初始化放在mLength初始化的前面的，我原来的顺序是这样的：
　　mLength 的初始化放在尺子的onSizeChangd()回调里面（这里在onLayout前），mCurrentScale的初始化放在onLayout完之后的回调，因为mCurrentScale的初始化之后的goToScale()方法就会用到mLength 。
　　我现在在我这边运行这个顺序是没问题的。
