### ISSUE TITLE
关于刻度尺最小单位的问题

### ISSUE THREAD

**Issue by wuliDJ** [totond/BooheeRuler#13]
请问如果我想自定义最小单位该如何去做？例如我想让每个刻度最小单位为10，滑动一个刻度就是增加10或者减少10。并且考虑到多种应用场景，我想让显示的数字不带小数点，全部显示整数，这个该如何处理？最近项目用到大神的框架，希望能指点一下

**Comment by wuliDJ** [comment]
通过改动源代码实现了项目的需求，不过建议大神还是考虑下这种情况，增加框架的灵活性，谢谢！

**Comment by totond** [comment]
感谢提出的意见，最新的0.1.4版本已经实现这个功能，通过factor属性设置最小单位。
