### ISSUE TITLE
使用 java 代码动态设置 scale 时，各种 Bug

### ISSUE THREAD

**Issue by madongqiang2201** [totond/BooheeRuler#14]
使用 java 代码设置 minScale 和 maxScale 以及 currentScale 时，返回的数值不对，而且莫名奇妙，，，

**Comment by totond** [comment]
不好意思，能具体描述下情况吗，如输入什么，返回什么，之前好像改了好多，都忘记改这些set方法了，我等下下班看一看，谢谢

**Comment by madongqiang2201** [comment]
把布局文件中设置 scale 的属性删掉，改为使用代码设置，然后尺子上选中的数值和 KgNumberLayout 上显示的数值对不上，KgNumberLayout 上显示的数值好像是各种 scale 在 BooheeRuler 里设置的的默认值计算的，现象很容易复现，你可以把布局文件中设置 scale的属性删掉，改成代码设置就可以复现

**Comment by totond** [comment]
刚刚吃完饭的时候看了一下，和你说的一样，应该是因为setXX属性之后，尺子的一些属性还没刷新，我在set方法里面调用init()方法之后就正常了，但这样会导致每次set方法都会init()重新初始化，虽然这样消耗的时间不长，但是毕竟是做了多余的操作。你说是前面这种解决方法好，还是开放init()方法，让用户调用完set方法之后重新init()刷新一下好呢？或者你有没更好的建议呢？

**Comment by madongqiang2201** [comment]
我也没有什么好思路，测试过程中，还发现了手动设置 scale 时，滑倒最后没有边界的问题(滑到没有刻度的地方还能滑动)，没有滑动边界的问题重新 init 并不能解决，推测可能是有一部分值是在 onSizeChange里面计算的，重新代码设值之后，那一部分值并没有重新计算导致的

**Comment by totond** [comment]
- 刚刚改完了，最后还是因为set方法太多了，决定开放一个refreshRuler()方法，让用户每次set方法改变属性完之后调用。
 - refreshRuler()方法里面包含了重画光标Drawable，InnerRuler的init初始化，还有onSizeChangd里面的计算操作，应该包含全了，测试过在View未Draw前动态设置属性和Draw之后动态设置属性都没问题了。
 - 改完发布了0.1.5版本。
 - 非常感谢提出的Bug，如果后面还有问题的话请多多指教啦^_^！
