### ISSUE TITLE
mCurrentScale的值可能会引起的一个无限绘制的问题

### ISSUE THREAD

**Issue by Lesences** [totond/BooheeRuler#15]
您好，在浏览了您的代码之后，我发现一个可能存在的问题，如题：
   
    如果说mCurrentScale 无限趋近其近似整数的时候，理论上将会一直循环执行scrollBackToCurrentScale()方法
   例如 mCurrentScale = 10.991211……，mCurrentScale!=Math.round(mCurrentScale),这个不等式将永远会成立，我觉得是不是应该再加一个处理精度的方法，防止无限绘制下去。

**Comment by totond** [comment]
你好，我觉得理论上是不会无限循环的，因为你可以看这个判断条件的前置条件：

```
if(!mOverScroller.computeScrollOffset())
```
这代表每一个OverScroller的最后一次滑动才会符合，所以就算有一次是OverScroller滑动到无限趋近其近似整数就停下来了，而导致要再执行多一个惯性滑动，但是下一次惯性滑动肯定会有位移，这样就应该会到达整点了，因为总路程就那么0.00几。
所以说我觉得最多就执行两次（出现两次是在OverScroller自身计算出错，还没达到整点就停下来的情况下，不知道会不会有这个情况，我没研究过它的源码，而我看过ValueAnimator是会有可能出错的），事实上我测试了几十次，都是只执行一次的。
不知道你觉得这个解释怎样呢，谢谢提出想法哈哈。

**Comment by totond** [comment]
- 刚刚回顾代码的时候又想起你提的这个问题，把间隔调大的情况下再测试，发现很容易会出现执行几次的情况，虽然没有无限次，但是的确会多执行几次绘制，应该真的是OverScroller计算的精度问题。
 - 所以我把判断条件改成(Math.abs(mCurrentScale - Math.round(mCurrentScale )) > 0.001f)，这样就没有这个问题了
