### ISSUE TITLE
代码中设置setCurrentScale无效

### ISSUE THREAD

**Issue by star-andy** [totond/BooheeRuler#16]
![image](https://user-images.githubusercontent.com/15726024/35520913-5e88782c-0553-11e8-89da-2ed94e262d21.png)

**Comment by totond** [comment]
使用setCurrentScale方法是不用刷新的，之前在README忘了说，不好意思，等下补充回去。所以把setCurrentScale放到最后就没问题了，至于这样放为什么有问题，我等下中午debug看看，谢谢

**Comment by star-andy** [comment]
好的  了解了   非常感谢    还想问下 如果factor设置为0.5      年龄的这个.0可以去掉吗？
![image](https://user-images.githubusercontent.com/15726024/35545180-ca2b8060-05a8-11e8-967a-dcd70061f4aa.png)

**Comment by totond** [comment]
这个要修改源码了，因为你要的是显示上是没有小数点，但是实际上结果是有0.5这种情况。
你可以给RulerStringUtil增加一个方法，这个方法代码复制它里面的resultValueOf()，然后对计算结果强制转换成整数或者Math.round()四舍五入，然后在具体要用的尺子里面的onDraw()方法里面的画字那里把这个你新写的方法替换掉resultValueOf()，然后尺子的结果还是用原来的resultValueOf()处理，这样应该就可以了。但是我觉得年龄的话，不是把factor设为1更好吗

**Comment by star-andy** [comment]
好的   非常感谢
