### ISSUE TITLE
咱们这个控件放到ViewPager会出现滑动不了的现象

### ISSUE THREAD

**Issue by yuzhongxingke** [totond/BooheeRuler#17]
我是使用SmartTabLayout+ViewPager;ViewPager中的Fragment中使用BooheeRuler，会出现滑动不了的现象，请问这个能帮解决一下吗？

**Comment by totond** [comment]
你好，根据你的描述，这个现象应该是ViewPager和BooheeRuler之间有滑动冲突导致的，大概是ViewPager拦截了BooheeRuler所需要的触摸事件。
　　解决滑动冲突的方式是根据你的业务需求而变化的，所以我建议你搜索一下如何解决ViewPager和ScrollView滑动冲突，把BooheeRuler当作一个ScrollView，应该就可以解决这个问题了。
　　解决之后有空的话可以跟我说下，我看能不能或者有没必要集成到BooheeRuler里面，谢谢啦。
