### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by wuhuaqing** [totond/BooheeRuler#18]
你在 HorizontalRuler 的scrollBackToCurrentScale 和 fling 方法中调用了 invalidate()方法，为什么它的子类的ondraw()方法没有调用呢？

**Comment by totond** [comment]
@wuhuaqing 
 - 你测试的时候是在什么观察到它没有调用的呢？我这里看是只要它滑动，就会有调用的。
 - 在这里这样写invalidate()是因为OverScroller只是一个计算滑动距离的辅助类，每次滑动的时候会回调computeScroll，然后实现下次滑动，然后这样循环直到滑动完毕。
