### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by eson-yunfei** [totond/BooheeRuler#2]
有一些APP需要设置标尺的横向和纵向，另外 公英制 的尺度是不一样的，可以考虑加一下。个人建议，仅供参考。

**Comment by totond** [comment]
谢谢eson-yunfei的建议：
 - 纵向的方式我会考虑做一下，这个应该不难。
 - 公英制切换的话，有开放出来的自定义可以改变单位，还有刻度之间的间距。从0.0.5版本开始，我开放出来的count属性有可以改动尺子每个大格子里面包含多少个小格子。不知道这样子改一下单位和这个count能不能实现公英制的切换呢？
