### ISSUE TITLE
急急急！！和scorllView冲突！速度解决下！

### ISSUE THREAD

**Issue by chenenqiang12345** [totond/BooheeRuler#20]
急急急！！和scorllView冲突！速度解决下！

**Comment by awq14789** [comment]
我在onTouchEvent里加了一句
`getParent().requestDisallowInterceptTouchEvent(true);`
以屏蔽父view里的touch方法，可以试一下

**Comment by totond** [comment]
请参考https://github.com/totond/BooheeRuler/issues/17
