### ISSUE TITLE
轮廓线没有画出来

### ISSUE THREAD

**Issue by levianye** [totond/BooheeRuler#24]
应该是InnerRuler 这个类里面mOutLinePaint没有设置setAntiAlias(true)，所以轮廓线没有画出来，建议加这个，或者添加一个属性可以设置轮廓线的宽度的，超过setStrokeWidth超过1的应该也能显示出来

**Comment by totond** [comment]
setStrokeWidth(0)按道理是应该设置1px的宽度，可能是测试机的分辨率太高了，导致看不到？感觉和抗锯齿没关系，不过后面我会把抗锯齿和设置宽度方法的开放都加上，谢谢建议
