### ISSUE TITLE
如果刻度尺在scrollview这种布局里面滑动会很卡

### ISSUE THREAD

**Issue by levianye** [totond/BooheeRuler#25]
如果刻度尺在被scrollview这样的布局包裹的情况下，滑动会有卡顿的感觉，建议在onTouchEvent里面加上处理，我这里重写处理后感觉非常流畅，建议您可以加上，这里是我的处理方式

public boolean onTouchEvent(MotionEvent event) {
        ViewGroup parent = (ViewGroup) getParent();
        float currentX = event.getX();
        //开始速度检测
        if (mVelocityTracker == null) {
            mVelocityTracker = VelocityTracker.obtain();
        }
        mVelocityTracker.addMovement(event);

        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                parent.requestDisallowInterceptTouchEvent(true);
                if (!mOverScroller.isFinished()) {
                    mOverScroller.abortAnimation();
                }

                mLastX = currentX;
                break;
            case MotionEvent.ACTION_MOVE:
                float moveX = mLastX - currentX;
                mLastX = currentX;
                scrollBy((int) (moveX), 0);
                break;
            case MotionEvent.ACTION_UP:
                //处理松手后的Fling
                mVelocityTracker.computeCurrentVelocity(1000, mMaximumVelocity);
                int velocityX = (int) mVelocityTracker.getXVelocity();
                if (Math.abs(velocityX) > mMinimumVelocity) {
                    fling(-velocityX);
                } else {
                    scrollBackToCurrentScale();
                }
                //VelocityTracker回收
                if (mVelocityTracker != null) {
                    mVelocityTracker.recycle();
                    mVelocityTracker = null;
                }
                releaseEdgeEffects();
                parent.requestDisallowInterceptTouchEvent(false);
                break;
            case MotionEvent.ACTION_CANCEL:
                if (!mOverScroller.isFinished()) {
                    mOverScroller.abortAnimation();
                }
                //回滚到整点刻度
                scrollBackToCurrentScale();
                //VelocityTracker回收
                if (mVelocityTracker != null) {
                    mVelocityTracker.recycle();
                    mVelocityTracker = null;
                }
                releaseEdgeEffects();
                parent.requestDisallowInterceptTouchEvent(false);
                break;
        }
        return true;
    }
主要就是加上requestDisallowInterceptTouchEvent解决垂直和水平的滑动冲突即可
最后非常感谢作者开源的这个控件，写的非常棒，结构清晰，可读性非常棒，帮了很大的忙，真的非常感谢！！

**Comment by totond** [comment]
感谢提出建议，其实你可以提交PR让我merge一下的，这样的话更加清晰地说明改动，你要这两天提交么，圣诞节后我应该有空加入你的代码，更新一个版本

**Comment by levianye** [comment]
已经提交了，你可以看下有没有问题，我重写后测试还是效果很好的，应该能解决各种嵌套在viewpager或者scrollview里面滑动冲突的问题
