### ISSUE TITLE
偶尔会出现InnerRuler 这个类里面重载方法computeScroll无限次被调用

### ISSUE THREAD

**Issue by levianye** [totond/BooheeRuler#28]
我使用过程中偶尔出现滑动过程中卡死现象，发现是这个方法被不停的调用，这个暂时还不清楚哪里出现了问题导致这个方法被无限次调用导致卡死

**Comment by levianye** [comment]
就是有几个数字经常触发这个方法无限次调用，比如我这里，单个刻度100，currentScale为1038的时候就基本必现，值为103800，好奇怪的问题
@Override
    public void computeScroll() {
        if (mOverScroller.computeScrollOffset()) {
            scrollTo(mOverScroller.getCurrX(), mOverScroller.getCurrY());
//这是最后OverScroller的最后一次滑动，如果这次滑动完了mCurrentScale不是整数，则把尺子移 动到最近的整数位置
            if (!mOverScroller.computeScrollOffset() && mCurrentScale != Math.round(mCurrentScale)){
//                Log.d("ruler", "computeScroll: " + mCurrentScale);
                //Fling完进行一次检测回滚
                scrollBackToCurrentScale();
            }
            invalidate();
        }
    }
这个方法不知道为啥会被无限次调用，仔细观察的话，在无限调用的时候，指示线和刻度尺的线有一点细微的偏差没有重叠，正常的不会无限调用的刻度是完全重合不会有偏差的，这个是刻度转成坐标偏差造成的吗？

**Comment by totond** [comment]
#15 这个问题我记得是改了的，然后现在发现远程仓库的居然没有变化，我想起来发现是我换电脑导致本地的commit好像没有提交，不好意思，我今晚下班看下有没有空提交更新之前的所有问题

**Comment by levianye** [comment]
我把这个判断条件if (!mOverScroller.computeScrollOffset() && mCurrentScale != Math.round(mCurrentScale))改成if (!scrollOffset && Math.abs(mCurrentScale - Math.round(mCurrentScale )) > 0.001f )好像一样的哎，这个精度是不是还要大一点？比如0.001*mFactor之类的？考虑到我这个单个刻度是100，这个是不是要乘以刻度乘积因子mFactor？我这里无限调用的情况这个mCurrentScale=1037.9286，差值是0.0714>0.001所以判断条件一直满足，就一直被调用，如果是0.1的话那么就不会再调用了，不过我改成if (!scrollOffset && Math.abs(mCurrentScale - Math.round(mCurrentScale )) > 0.1f )这个的情况下，无限调用情况是没有了，但是最中间的光标就没有完全重叠的停留在对应刻度了，有那么一点点偏差，仔细看还是能看出来的。
所以我在想是不是HorizontalRuler或者VerticalRuler这两个类里面的方法scrollXtoScale和scaleToScrollY根据scale算出来的坐标有那么一点点误差这样导致的？

**Comment by levianye** [comment]
<yanzhikai.ruler.BooheeRuler
                android:id="@+id/monthly_number_ruler"
                android:layout_width="match_parent"
                android:layout_height="56dp"
                android:layout_marginTop="10dp"
                app:textMarginHead="22dp"
                app:rulerStyle="BOTTOM_HEAD"
                app:numberTextColor="#D4D2D2"
                app:numberTextSize="9sp"
                app:scaleInterval="5dp"
                app:bigScaleLength="17dp"
                app:bigScaleWidth="1dp"
                app:smallScaleLength="10dp"
                app:smallScaleWidth="1dp"
                app:scaleColor="#E5E5E5"
                app:cursorDrawable="#FFAD01"
                app:cursorHeight="56dp"
                app:cursorWidth="1dp"
                app:currentScale="2000"
                app:factor="100"
                app:minScale="0"
                app:maxScale="3000"/>
我的刻度尺的xml是这样的，现在发现app:scaleInterval这个属性我设置为5dp或者8dp的时候出现了无限调用的现象，如果是6dp,或者7dp的时候数值基本不会有偏差，日志看到有偏差大概也是在0.001这样，所以也正常，其他值还没测试看下，算出来的scale基本都是正常的，我的测试的手机是小米Mix2，所以是不是和这个像素密度算出来的正常值相差有关？你可以把我这个xml属性拿去测试下，用小米Mix2测试，看看我的这个你那边是不是也能复现出来，当然这个值我觉得还和大小刻度宽度有关，所以应该是兼容性问题

**Comment by totond** [comment]
- 关于mFactor：它只是一个对外放大显示的因子，不会影响到内部的px值移动，简单来说就是一格长度所代表的意义，如默认的一格是0.1，所以不用它来判断是否滑动结束
 - 关于这个无限回弹的问题，我觉得是你说的scrollXtoScale和scaleToScroll造成的精度丢失有关，因为这些方法最后的结果都是把float强制转换为int（px是整型），所以在屏幕密度比较高的手机，会比较容易出现这个情况（计算出来的结果小数点丢的很多）丢失了之后，回弹的目标（startScroll里面的dx或者dy）就偏了，然后滑动到最后currentScale还是和整数位置相差相同的value，无限循环
 - 我能想到的这个问题解决方法：scrollXtoScale和scaleToScroll的结果用Math.round()处理，然后在scrollBackToCurrentScale里面对计算出来的偏差值dx做判断，低于某一个阈值就不用OverScroller了，直接scrollTo，这个阈值应该是一个肉眼几乎无法区分是连续滑动还是单次滑动的距离，然后是基于屏幕密度的（dp）
 - 因为最近加班比较多，估计这个要放假才加上

**Comment by levianye** [comment]
是的，最开始我就想这个精度丢失问题导致的，所以我想是不是可以换个思路，数字放大转成int来处理这样？
PS，我想我已经解决了，现在测试完全正常！就是做一下数字放大处理，以免精度丢失这样，我的处理是这样的
加一个方法
private float scaleToScrollFloatX(float scale) {
        float scaleValue = scale * 100;
        return (((scaleValue - mParent.getMinScale() * 100) / mMaxLength * mLength) +100 * mMinPosition);
    }
然后把重载方法scrollBackToCurrentScale里面的这一句：
mOverScroller.startScroll(getScrollX(), 0, scaleToScrollX(Math.round(mCurrentScale)) - getScrollX(), 0, 500);
改为
mOverScroller.startScroll(getScrollX(), 0, Math.round((scaleToScrollFloatX(Math.round(mCurrentScale))-100*getScrollX())/100), 0, 500);
测试下来运行十分完好，刻度完全对齐，也不会有无限调用的情况了，如果可以，我这个提交上去你合并掉，我暂时就是改了HorizontalRuler，等下VerticalRuler一起改掉

**Comment by totond** [comment]
已经合并代码，调整后发布了0.1.6版本，感谢你的贡献^_^！
