### ISSUE TITLE
询问Fling结束时的处理方式

### ISSUE THREAD

**Issue by ZhuLeon** [totond/BooheeRuler#6]
我在读你的代码时，感觉你对Fling结束时的处理方式很巧妙。恕我孤陋寡闻，是你自己想的还是有什么参考依据？
下面这段代码：
```java
@Override
public void computeScroll() {
    if (mOverScroller.computeScrollOffset()) {
        scrollTo(mOverScroller.getCurrX(), mOverScroller.getCurrY());

        // 用这种方式判断Fling结束时刻，我觉得挺巧妙的
        if (!mOverScroller.computeScrollOffset() && mCurrentScale != Math.round(mCurrentScale)){
            //Fling完进行一次检测回滚
            scrollBackToCurrentScale();
        }
        invalidate();
    }
}
```

**Comment by totond** [comment]
谢谢，是我当时灵机一动想的哈。当时的想法是这样的：
　　因为找不到惯性滑动结束的回调，想到computeScroll() 方法里面是处理惯性滑动的计算，当时就想想能不能在这里处理，然后发现OverScroller.computeScrollOffset()判断的是计算是否开始，然后我就想它最后一次滑动肯定是返回false才会结束这个循环的。
　　一开始是没加后面的那个mCurrentScale != Math.round(mCurrentScale)判断条件，这样会发现computeScroll() 方法会一直不断的调用，因为scrollBackToCurrentScale()也需要惯性滑动，最后结束为false的时候又回滚变成true了嘛，所以我就想要不直接使用scrollTo()方法直接到达就算了，但是试了之后体验不是很好，所以又想了下发现可以加上一个“是否还没有滑动到目的点的判断条件“，来使尺子在惯性滑动结束而且在到达整刻度点的时候不再调用回滚。
