### ISSUE TITLE
关于Scroller.fling的请教

### ISSUE THREAD

**Issue by ysemylord** [totond/BooheeRuler#8]
你好。我在模仿薄荷卷尺的时候有一个问题：
调用Scroller.fling滑到最后一段距离有一个明显的减速过程，但是我发现你的和薄荷的都没有这样。 
我的滑动处理的代码是下面这样的
```
  int action = event.getAction();
        switch (action) {
            case MotionEvent.ACTION_DOWN:

                if (!mFlingScroller.isFinished()) {
                    mFlingScroller.abortAnimation();
                }
                int index = event.getActionIndex();
                mPointActivtyId = event.getPointerId(index);
                mLastX = event.getX();
                if (mVelocityTracker == null) {
                    mVelocityTracker = VelocityTracker.obtain();
                } else {
                    mVelocityTracker.clear();
                }
                mVelocityTracker.addMovement(event);
                break;
            case MotionEvent.ACTION_MOVE:
                mVelocityTracker.addMovement(event);
                int pointIndex = event.findPointerIndex(mPointActivtyId);
                if (pointIndex == -1) {
                    Log.i(TAG, "onTouchEvent: error index");
                    break;
                }

                float x = event.getX(pointIndex);
                float dx = x - mLastX;
                float scrollDx = -dx;

                scrollBy((int) scrollDx, 0);

                mLastX = x;

                break;
            case MotionEvent.ACTION_UP:
                mVelocityTracker.computeCurrentVelocity(1000, mMaximumFling);
                float xvel = VelocityTrackerCompat.getXVelocity(mVelocityTracker,
                        mPointActivtyId);
                Log.i(TAG, "onTouchEvent: " + xvel);

                if (Math.abs(xvel) > mMinimumFling) {
                    mFlingScroller.fling(
                            getScrollX(), getScrollY(),
                            -(int) xvel, 0,//数据设为计算出的速度的相反值
                            leftMaxScorll, rightMaxScroll,
                            0, 0);
                    invalidate();
                } else {
                    ajustScrollX();
                }


                mPointActivtyId = -1;
                mLastX = -1;


                break;
            case MotionEvent.ACTION_CANCEL:
                mPointActivtyId = -1;
                mLastX = -1;
                mVelocityTracker.recycle();
                break;
        }
```

**Comment by totond** [comment]
你好，能不能直接把在computeScroll()方法里面，把getScrollX的值输出出来给我看一下了，这样有便于查看什么时候发生减速，减速是多少。

**Comment by ysemylord** [comment]
下面是发生减速时的scrollX值，是一个像素一个像素递减的，有办法设置fling的加速度之类的吗?
11-10 14:57:27.399 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 93
11-10 14:57:27.415 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 93
11-10 14:57:27.432 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 90
11-10 14:57:27.449 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 88
11-10 14:57:27.465 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 85
11-10 14:57:27.482 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 83
11-10 14:57:27.499 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 81
11-10 14:57:27.515 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 78
11-10 14:57:27.531 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 76
11-10 14:57:27.548 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 74
11-10 14:57:27.564 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 71
11-10 14:57:27.580 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 69
11-10 14:57:27.597 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 67
11-10 14:57:27.613 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 65
11-10 14:57:27.630 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 63
11-10 14:57:27.646 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 61
11-10 14:57:27.663 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 59
11-10 14:57:27.679 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 57
11-10 14:57:27.696 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 55
11-10 14:57:27.712 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 53
11-10 14:57:27.729 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 52
11-10 14:57:27.745 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 50
11-10 14:57:27.762 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 48
11-10 14:57:27.778 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 47
11-10 14:57:27.795 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 45
11-10 14:57:27.811 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 43
11-10 14:57:27.827 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 42
11-10 14:57:27.844 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 41
11-10 14:57:27.861 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 39
11-10 14:57:27.877 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 38
11-10 14:57:27.893 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 36
11-10 14:57:27.910 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 35
11-10 14:57:27.926 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 34
11-10 14:57:27.943 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 33
11-10 14:57:27.959 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 32
11-10 14:57:27.976 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 30
11-10 14:57:27.992 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 29
11-10 14:57:28.009 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 28
11-10 14:57:28.025 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 27
11-10 14:57:28.041 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 26
11-10 14:57:28.058 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 25
11-10 14:57:28.074 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 24
11-10 14:57:28.091 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 23
11-10 14:57:28.107 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 22
11-10 14:57:28.122 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 22
11-10 14:57:28.140 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 21
11-10 14:57:28.157 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 20
11-10 14:57:28.173 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 19
11-10 14:57:28.189 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 18
11-10 14:57:28.204 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 18
11-10 14:57:28.222 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 17
11-10 14:57:28.239 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 16
11-10 14:57:28.254 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 16
11-10 14:57:28.272 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 15
11-10 14:57:28.288 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 14
11-10 14:57:28.303 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 14
11-10 14:57:28.321 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 13
11-10 14:57:28.338 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 12
11-10 14:57:28.353 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 12
11-10 14:57:28.371 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 11
11-10 14:57:28.386 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 11
11-10 14:57:28.404 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 10
11-10 14:57:28.419 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 10
11-10 14:57:28.437 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 9
11-10 14:57:28.452 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 9
11-10 14:57:28.468 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 9
11-10 14:57:28.486 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 8
11-10 14:57:28.501 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 8
11-10 14:57:28.519 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 7
11-10 14:57:28.534 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 7
11-10 14:57:28.550 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 7
11-10 14:57:28.568 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 6
11-10 14:57:28.583 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 6
11-10 14:57:28.601 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 5
11-10 14:57:28.616 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 5
11-10 14:57:28.633 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 5
11-10 14:57:28.649 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 5
11-10 14:57:28.667 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 4
11-10 14:57:28.682 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 4
11-10 14:57:28.698 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 4
11-10 14:57:28.716 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 3
11-10 14:57:28.731 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 3
11-10 14:57:28.748 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 3
11-10 14:57:28.764 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 3
11-10 14:57:28.780 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 3
11-10 14:57:28.798 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 2
11-10 14:57:28.813 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 2
11-10 14:57:28.830 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 2
11-10 14:57:28.846 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 2
11-10 14:57:28.863 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 2
11-10 14:57:28.881 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.897 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.913 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.929 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.946 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.962 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.979 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:28.995 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1
11-10 14:57:29.012 17402-17402/com.xyb.tape I/MyScrollView: computeScroll: getScrollX 1

**Comment by ysemylord** [comment]
我看了下你的项目中scrollX的变化
11-10 15:08:36.331 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX 139
11-10 15:08:36.348 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -9
11-10 15:08:36.366 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -176
11-10 15:08:36.382 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -323
11-10 15:08:36.398 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -471
11-10 15:08:36.415 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.430 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.446 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.463 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.479 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.496 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.512 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540
11-10 15:08:36.528 18824-18824/yanzhikai.booheeruler I/ruler: computeScroll: getScrollX -540

**Comment by ysemylord** [comment]
我找到原因了。
 fling(int startX, int startY, int velocityX, int velocityY,
            int minX, int maxX, int minY, int maxY) 。
因为最小的偏移量为0，所以minX设置的是0，当要减到0的时候，就会减速减到0；
所以我将miniX设置成一个比零小的数（如:500）,这样要减到0的时候就不会减速，又因为我重写scrollTo限制了最小偏移量为0的，所以也不会超超过最小的偏移量。

但是 我看你的项目中minX设置的就是最小偏移量，这就不知道怎么回事了

**Comment by totond** [comment]
我刚刚log了一下BooheeRuler的Fling时候的getScrollX()值，发现也是有减速的，你之前log的是不是因为甩尾速度过小没有触发Fling的情况呢？

```
11-10 03:35:25.148 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: -384
11-10 03:35:36.841 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 33
11-10 03:35:36.856 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 149
11-10 03:35:36.874 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 227
11-10 03:35:36.923 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 549
11-10 03:35:36.974 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 886
11-10 03:35:37.025 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 1161
11-10 03:35:37.079 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 1421
11-10 03:35:37.119 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 1577
11-10 03:35:37.157 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 1743
11-10 03:35:37.200 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 1895
11-10 03:35:37.242 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2026
11-10 03:35:37.279 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2133
11-10 03:35:37.314 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2221
11-10 03:35:37.350 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2313
11-10 03:35:37.385 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2390
11-10 03:35:37.430 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2479
11-10 03:35:37.481 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2569
11-10 03:35:37.512 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2618
11-10 03:35:37.548 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2671
11-10 03:35:37.590 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2725
11-10 03:35:37.633 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2775
11-10 03:35:37.695 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2833
11-10 03:35:37.730 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2864
11-10 03:35:37.769 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2894
11-10 03:35:37.831 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2933
11-10 03:35:37.882 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2958
11-10 03:35:37.918 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2974
11-10 03:35:37.980 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 2993
11-10 03:35:38.016 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3002
11-10 03:35:38.065 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3010
11-10 03:35:38.116 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3015
11-10 03:35:38.164 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3016
11-10 03:35:38.216 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3016
11-10 03:35:38.255 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3017
11-10 03:35:38.294 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3018
11-10 03:35:38.330 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3018
11-10 03:35:38.378 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3019
11-10 03:35:38.413 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3019
11-10 03:35:38.449 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3019
11-10 03:35:38.477 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3019
11-10 03:35:38.515 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020
11-10 03:35:38.552 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020
11-10 03:35:38.583 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020
11-10 03:35:38.628 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020
11-10 03:35:38.668 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020
11-10 03:35:38.699 6368-6368/yanzhikai.booheeruler D/ruler: getScrollX: 3020

```

　　我大力滑动，上面可以看到明显的减速现象，至于最小偏移量，我觉得不关减不减速的事情，这个是确定滑动界限的，我那个mMinPositionX虽然初始值是0，但是后面是在onSizeChanged()方法里面动态决定它的值，为控件宽度一半的负数，这样可以确保往右滑的情况滑到底时是停在控件中间。
