### ISSUE TITLE
drawScale方法

### ISSUE THREAD

**Issue by xiaoxiangyeyu123** [totond/BooheeRuler#9]
请问 drawScale方法中if (locationX > getScrollX() - mDrawOffset && locationX < (getScrollX() + canvas.getWidth() + mDrawOffset))
判断什么的？

**Comment by totond** [comment]
你好，原本如果不加这个判断那么每次onDraw都会把整个刻度尺的刻度画出来，实际上我们需要显示的只是当前屏幕上的一部分加上mDrawOffset的一小部分而已，所以就取范围为[getScrollX() - mDrawOffset,getScrollX()- mDrawOffset + canvas.getWidth() + mDrawOffset]的刻度，至于加上mDrawOffset这一小部分，是为了让刻度的绘制前后多半大格，这样可以提前显示出下面的数字，让过渡不会变得那么突兀。
